run:
  go: '1.23'
  deadline: 210s
  timeout: 10m

issues:
  exclude-dirs:
    - mocks
    - '.*_mock'
  exclude-files:
    - '.*_mock.go'
    - ".*\\.pb\\.go$"

linters-settings:
  dupl:
    threshold: 250
  goconst:
    min-len: 5
    min-occurrences: 5
  gocritic:
    disabled-checks:
      - ifElseChain
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 364
      rangeValCopy:
        sizeThreshold: 364
        skipTestFuncs: true
  gofumpt:
    simplify: true
  goimports:
    local-prefixes: github.com/GetStream/stream-cli
