version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/stream-cli/
    binary: stream-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    # By default goreleaser wants to add CHANGELOG, README and LICENSE to the zip package which is annoying.
    # This is a workaround to not include them. https://github.com/goreleaser/goreleaser/issues/602
    files:
      - none*

homebrew_casks:
  - name: stream-cli
    homepage: https://github.com/GetStream/stream-cli
    description: Manage your Stream applications easily.
    repository:
      owner: GetStream
      name: stream-cli
