# This file was generated by GoReleaser. DO NOT EDIT.
cask "stream-cli" do
  version "1.10.1"

  on_macos do
    on_intel do
      sha256 "54d88ff97ead780350703b99698b7b5d3e002d40d2852ae2bb39bc226c8601fc"
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e7b03dae1c455af68aef952e9cec69442b6e975a08cf2c4584a6b33dee3bb3df"
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b82079870ef3b59fcc46660e882c46d5e0561a03448f6ee73d40d667373094d3"
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ced488c7d5dd2494bd8e843999c56fac82cf01bde2465046e9bcc7d22cd1c75b"
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Linux_arm64.tar.gz"
    end
  end

  name "stream-cli"
  desc "Manage your Stream applications easily."
  homepage "https://github.com/GetStream/stream-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stream-cli"

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}"
  end

  # No zap stanza required

end
