# This file was generated by GoReleaser. DO NOT EDIT.
cask "stream-cli" do
  name "stream-cli"
  desc "Manage your Stream applications easily."
  homepage "https://github.com/GetStream/stream-cli"
  version "1.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stream-cli"

  on_macos do
    on_intel do
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Darwin_x86_64.tar.gz"
      sha256 "028d702b7741dfd82347143e76a998fe57fadd0e7036892bb52a09d6138bbcf8"
    end
    on_arm do
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Darwin_arm64.tar.gz"
      sha256 "fb666e56e36449e6edf6708188113bcccf1bd7e0a20941439ebe0e76143dc48d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Linux_x86_64.tar.gz"
      sha256 "0aad5d2555ebc44d7f9827ca127ed7119bdda9ab070e27b79d189e1f744fc028"
    end
    on_arm do
      url "https://github.com/GetStream/stream-cli/releases/download/v#{version}/stream-cli_Linux_arm64.tar.gz"
      sha256 "33d3cb2a235c8cbf59fb222c4821281b7d11814db3c3e6e5cb460fe411d25e5c"
    end
  end

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}"
  end

  # No zap stanza required
end
