name: Lint

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 👮 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit message linter
        uses: wagoid/commitlint-github-action@v5

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Tidy
        run: go mod tidy -v && git diff --no-patch --exit-code || { git status;  echo 'Unchecked diff, did you forget go mod tidy again?' ; false ; };

      - name: Linters
        run: make lint

